export const TYPES = {
  UserRepositoryDB: Symbol.for("UserRepositoryDB"),
  AuthService: Symbol.for("AuthService"),
  AuthController: Symbol.for("AuthController"),
  UserService: Symbol.for("UserService"),
  UserController: Symbol.for("UserController"),
  ResearcherRequestRepositoryDB: Symbol.for("ResearcherRequestRepositoryDB"),
  ResearcherRequestService: Symbol.for("ResearcherRequestService"),
  ResearcherRequestController: Symbol.for("ResearcherRequestController"),
  ArtifactRepositoryDB: Symbol.for("ArtifactRepositoryDB"),
  ArtifactService: Symbol.for("ArtifactService"),
  ArtifactController: Symbol.for("ArtifactController"),
  ArtifactCollectionRepositoryDB: Symbol.for("ArtifactCollectionRepository"),
  ArtifactCollectionService: Symbol.for("ArtifactCollectionService"),
  ArtifactCollectionController: Symbol.for("ArtifactCollectionController"),
  CommunityRepositoryDB: Symbol.for("CommunityRepositoryDB"),
  CommunityService: Symbol.for("CommunityService"),
  CommunityController: Symbol.for("CommunityController"),
  CommunityUserRepositoryDB: Symbol.for("CommunityUserRepositoryDB"),
  CommunityUserService: Symbol.for("CommunityUserService"),
  CommunityUserController: Symbol.for("CommunityUserController"),
  PostRepositoryDB: Symbol.for("PostRepositoryDB"),
  PostService: Symbol.for("PostService"),
  PostController: Symbol.for("PostController"),
  PostMediaRepositoryDB: Symbol.for("PostMediaRepositoryDB"),
  PostMediaService: Symbol.for("PostMediaService"),
  PostMediaController: Symbol.for(" PostMediaController"),
};
